"""sync schema (course fields)

Revision ID: 5eaaedd5b39e
Revises: e19fa6dc390e
Create Date: 2025-12-23 21:42:17.533006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5eaaedd5b39e'
down_revision: Union[str, Sequence[str], None] = 'e19fa6dc390e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('courses', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.alter_column('courses', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'level',
               existing_type=mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('courses', 'instructor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'COMPLETED', 'CANCELED'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('enrollments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lectures', 'order_index',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lectures', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'comment',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('USER', 'ADMIN'),
               type_=sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False, length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False, length=50),
               type_=mysql.ENUM('USER', 'ADMIN'),
               existing_nullable=False)
    op.alter_column('reviews', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('lectures', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lectures', 'order_index',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('ACTIVE', 'COMPLETED', 'CANCELED'),
               nullable=False)
    op.alter_column('courses', 'instructor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'level',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED'),
               nullable=False)
    op.alter_column('courses', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('courses', 'is_public')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
